# Generated by Django 2.0.6 on 2020-05-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_auto_20200513_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
