# Generated by Django 2.0.6 on 2020-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_autor_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default='True', verbose_name='Estado'),
        ),
    ]
